# Nombre del flujo de trabajo, aparecerá en la pestaña "Actions" de GitHub
name: Deploy Frontend to Hostinger

# Disparador: Este flujo se ejecuta cada vez que hay un push a la rama "main"
on:
  push:
    branches:
      - main

# Trabajos: Lista de tareas que el robot debe ejecutar
jobs:
  build-and-deploy:
    # El tipo de máquina que usará el robot (Ubuntu es estándar)
    runs-on: ubuntu-latest

    # Pasos: La secuencia de acciones a realizar
    steps:
      # 1. Descarga el código del repositorio a la máquina del robot
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js para que podamos usar npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Crea el archivo .env.production usando el secreto de GitHub
      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > frontend/.env.production

      # 4. Entra en la carpeta frontend e instala las dependencias
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      # 5. Construye la aplicación de producción
      - name: Build application
        run: |
          cd frontend
          npm run build

      # 6. Configura la clave SSH y añade el host a los hosts conocidos
      - name: Setup SSH and Known Hosts
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 65002 -H ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts

      # 7. Sube los archivos compilados a Hostinger vía rsync (usando la ruta absoluta)
      - name: Deploy to Hostinger via rsync
        run: |
          # Usamos la ruta absoluta al directorio de destino para evitar ambigüedades.
          # La estructura estándar de Hostinger es /home/USERNAME/domains/DOMAIN_NAME/public_html
          rsync -avz --delete -e "ssh -p 65002" ./frontend/dist/ ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:/home/${{ secrets.FTP_USERNAME }}/domains/techmartel.com/public_html


